sonar.projectKey=sharvani-Z_StoryBook
sonar.organization=sharvani-z
sonar.sources=src
sonar.language=js
sonar.host.url=https://sonarcloud.io
sonar.exclusions=**/*.test.*,**/*.spec.*,**/node_modules/**,**/dist/**,**/build/**