# sonar.projectKey=sharvani-Z_StoryBook
# sonar.organization=sharvani-z
# sonar.sources=src
# sonar.language=js
# sonar.host.url=https://sonarcloud.io
# sonar.exclusions=**/*.test.*,**/*.spec.*,**/node_modules/**,**/dist/**,**/build/**
# sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.projectKey=sharvani-Z_StoryBook
sonar.organization=sharvani-z
sonar.sources=src
sonar.host.url=https://sonarcloud.io

sonar.exclusions=**/*.test.*,**/*.spec.*,**/*.stories.*,**/node_modules/**,**/dist/**,**/build/**,**/.storybook/**,**/storybook-static/**,**/coverage/**,**/coverage/**/**,**/*.lcov,**/*.html,**/*.css,**/*.js.map,**/*.d.ts

sonar.test.exclusions=**/node_modules/**,**/.storybook/**,**/storybook-static/**

sonar.coverage.exclusions=**/.storybook/**,**/*.stories.*

sonar.javascript.lcov.reportPaths=coverage/lcov.info